### ISSUE TITLE
Override the click listener for cancel button in calc dialog

### ISSUE THREAD

**Issue by saikiran143** [maltaisn/calcdialoglib#18]
I want to show custom alert when i click 'cancel' in calc dialog. How could I override the operation??

**Comment by Croutonix** [comment]
There's currently no way to do this. If you could access the view in onCreateDialog, you could subclass the dialog and change the cancel button click listener but that's not currently possible. I don't really want to add a custom cancel listener since this is not a very common problem. So I'll make a new release soon with a `getView()` method to allow changing the cancel button listener.

It would look like this:
```java
public class CustomCalcDialog extends CalcDialog {

    @Override
    @NonNull
    public Dialog onCreateDialog(final Bundle state) {
        final Dialog dialog = super.onCreateDialog(state)

        final View view = getView();  // This method doesn't exist yet.
        final Button cancelBtn = view.findViewById(R.id.calc_btn_cancel);
        cancelBtn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                // Show your custom alert here
                dismissAllowingStateLoss();
            }
        });

        return dialog
    }
}
```
Would that work for you?

**Comment by maltaisn** [comment]
There's currently no way to do this. If you could access the view in onCreateDialog, you could subclass the dialog and change the cancel button click listener but that's not currently possible. I don't really want to add a custom cancel listener since this is not a very common problem. So I'll make a new release soon with a `getView()` method to allow changing the cancel button listener.

It would look like this:
```java
public class CustomCalcDialog extends CalcDialog {

    @Override
    @NonNull
    public Dialog onCreateDialog(final Bundle state) {
        final Dialog dialog = super.onCreateDialog(state)

        final View view = getView();  // This method doesn't exist yet.
        final Button cancelBtn = view.findViewById(R.id.calc_btn_cancel);
        cancelBtn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                // Show your custom alert here
                dismissAllowingStateLoss();
            }
        });

        return dialog
    }
}
```
Would that work for you?
